const projects = [
  {
    name: "Property Rental Web App",
    tech: [
      "Angular",
      "Firebase Authentication",
      "Firebase Storage",
      "Firestore Database",
      "Firebase Hosting",
      "Typescript",
    ],
    desc: "Property Rental is a hub for people looking to rent out or to lease out properties. It connects prospective tenants to people with property for rent in their area.",
    github: "https://github.com/tamirkifle/property-rental",
    hostedAt: "https://property-rental-fca0f.web.app/",
    coverImg: "property-rental.jpg",
  },
  {
    name: "Similar Faces: A Game",
    tech: [
      "Angular",
      "Microsoft Azure AI",
      "Face API",
      "Azure Blob Storage",
      "Typescript",
    ],
    desc: "Similar Faces: A Game was a project built during a AI bootcamp hosted by Microsoft and Gebeya Inc. A simple game where the goal is to guess the most similar face out of a list of faces comparing your instincts to Microsoft's Artificial Intelligence.",
    coverImg: "similar-faces.jpg",
  },
  {
    name: "Number to Amharic Text Converter",
    tech: ["Javascript", "npm"],
    desc: "A javascript package that tranforms normal (arabic) numbers into their amharic text counterparts.",
    github: "https://github.com/tamirkifle/number-to-amharic-text",
    hostedAt: "https://www.npmjs.com/package/number-to-amharic-text",
    coverImg: "number-to-amharic.png",
  },
  {
    name: "Portfolio Page",
    tech: [
      "Angular",
      "Firebase Authentication",
      "Firebase Storage",
      "Firestore Database",
      "Firebase Hosting",
      "Typescript",
    ],
    desc: "Property Rental is a hub for people looking to rent out or to lease out properties. It connects prospective tenants to people with property for rent in their area.",
    github: "https://github.com/tamirkifle/property-rental",
    hostedAt: "https://property-rental-fca0f.web.app/",
  },
  {
    name: "Grid Image Gallery",
    tech: [
      "Angular",
      "Firebase Authentication",
      "Firebase Storage",
      "Firestore Database",
      "Firebase Hosting",
      "Typescript",
    ],
    desc: "Property Rental is a hub for people looking to rent out or to lease out properties. It connects prospective tenants to people with property for rent in their area.",
    github: "https://github.com/tamirkifle/property-rental",
    hostedAt: "https://property-rental-fca0f.web.app/",
  },
  {
    name: "Responsive Image Slider component",
    tech: [
      "Angular",
      "Firebase Authentication",
      "Firebase Storage",
      "Firestore Database",
      "Firebase Hosting",
      "Typescript",
    ],
    desc: "Property Rental is a hub for people looking to rent out or to lease out properties. It connects prospective tenants to people with property for rent in their area.",
    github: "https://github.com/tamirkifle/property-rental",
    hostedAt: "https://property-rental-fca0f.web.app/",
  },
];

export default projects;
